services:
  vote:
    image: DOCKERHUB_USERNAME/vote:latest
    ports:
      - "8080:80"

  result:
    image: DOCKERHUB_USERNAME/result:latest
    ports:
      - "8081:80"

  worker:
    image: DOCKERHUB_USERNAME/worker:latest

  redis:
    image: redis:alpine

  db:
    image: postgres:15
